### PR TITLE
A few changes in the README and in the install script.

### PR DESCRIPTION
**Pull request by TuralTo**
I originally wanted to fix some grammar problems, but went too deep into it and fixed some inconsistencies, tried to make some sections more understandable, and a quality of life thing at the start of README. You are welcome to remove any unneeded parts. Had fun working on this, thank you!

### CODE REVIEW

**Comment by Ilya114** [comment]
Thanks

**Comment by Matews371** [comment]
Fix virgl bugs & add dri3 on mesa-virgl

**Comment by Matews371** [comment]
Fix the virgl it is not opening anything.  test to see there

**Comment by TuralTo** [comment]
> Fix the virgl it is not opening anything.  test to see there

Could you show the error log if possible?

**Comment by Matews371** [comment]
> > Conserte o virgl, ele não está abrindo nada. teste para ver lá
> 
> Você poderia mostrar o log de erros, se possível?

unfortunately I don't have box64 installed but you will see an error when you test box64droid virgl

**Pull request merged**
